### ISSUE TITLE
Filament V3

### ISSUE THREAD

**Issue by Spencer30** [RealMrHex/filament-modular#10]
Great package. Question - are you planning to support Filament V3 in the near future?

**Comment by RealMrHex** [comment]
@Spencer30
Thank you.
Yup, work in progress to support V3.
I'll close this issue for now, but please feel free to reopen it if you have any other questions.

**Comment by RealMrHex** [comment]
@Spencer30 V3 SupportL
https://github.com/RealMrHex/filament-modular-v3

**Comment by RealMrHex** [comment]
@Spencer30
**V3 Support:**
https://github.com/RealMrHex/filament-modular-v3
