### ISSUE TITLE
module:make-filament-resource doesnt find stub file

### ISSUE THREAD

**Issue by mahdimsr** [RealMrHex/filament-modular#6]
Hi.
Imused this command to create a resource

`php artisan module:make-filament-resource`

and it gives me this error:

```
iIlluminate\Contracts\Filesystem\FileNotFoundException 

File does not exist at path .../realmrhex/filament-modular/src/../stubs/Resource.stub.
```

it seems stub does not exist in the path and I could not find stubs in the repository either

**Comment by RealMrHex** [comment]
Hi @mahdimsr ,

Thank you for bringing this issue to our attention. I am currently looking into the error message you received and will do my best to resolve it as soon as possible.

Rest assured that I will keep you updated on my progress and let you know once the issue has been fixed.

Thank you for your patience.

Best regards.

**Comment by RealMrHex** [comment]
Dear @mahdimsr, It should be fixed now.
Test it and Feel free to re-open this issue if anything goes wrong.
Thanks for your report.
