### ISSUE TITLE
{{view}} wrong generate

### ISSUE THREAD

**Issue by sorethea** [RealMrHex/filament-modular#8]
In case Module name "App" the {{view}} should be "app::admin.widgets.###" but "admin::widgets.###" generated.

**Comment by RealMrHex** [comment]
Thanks for your report.
I will check it and patch the bug ASAP

**Comment by RealMrHex** [comment]
> In case Module name "App" the {{view}} should be "app::admin.widgets.###" but "admin::widgets.###" generated.

@sorethea 
Can you explain the steps that led you to encounter the issue?

**Comment by sorethea** [comment]
When running the page generated command for example: " *php artisan
module:make-filament-page Test App*"
this is a class Test page generated:
<?php

namespace Modules\App\Admin\Pages;

use Filament\Pages\Page;

class Test extends Page
{
protected static ?string $navigationIcon = 'heroicon-o-document-text';

protected static string $view = 'admin::pages.test';
}

Should be $view = 'app::admin.pages.test';

**Comment by RealMrHex** [comment]
@sorethea Gotcha, Thanks for your report, ill fix it tonight
