### ISSUE TITLE
Will it support filament v3?

### ISSUE THREAD

**Issue by 000yuying** [RealMrHex/filament-modular#9]
Will there be a chance to support filament v3 in the near future?

**Comment by RealMrHex** [comment]
Yes!
Release will be accessible after the Filament and Livewire 3 touch the stable flag.

**Comment by 000yuying** [comment]
Oh! got it ~
Thanks and looking forward to it ☺️

**Comment by RealMrHex** [comment]
@000yuying
**V3 Support:**
https://github.com/RealMrHex/filament-modular-v3
